### PR TITLE
Update deps to the latest charm.v4.

### PR DESCRIPTION
**Pull request by frankban**
Update the example charm actions used for
tests so that it conforms to the new syntax.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/784/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by rogpeppe** [comment]
LGTM
I wonder if this should really have caused a new charm major version though.

**Comment by frankban** [comment]
@rogpeppe yeah I had the same thought. I guess actions are not really used yet, so...
Anyway, thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
