### PR TITLE
update to latest charmrepo version with Published field removed

### PR DESCRIPTION
**Pull request by rogpeppe**
Also update other deps that were newer in charmrepo than charmstore.

### CODE REVIEW

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1654/
Test PASSed.

**Pull request merged**
