### PR TITLE
fix charmd by adding readConfig function

### PR DESCRIPTION
**Pull request by rogpeppe**
The ReadConfig function isn't in the new version of the charmstore package.
Creating as a private function inside charmd until need is demonstrated for
it elsewhere. The readConfig code and test is copied from _old.

### CODE REVIEW

**Comment by jrwren** [comment]
:+1: LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/78/

**Comment by rogpeppe** [comment]
Merging with only one review as this fixes trunk.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmstore-merge/50

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/80/

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmstore-merge/51

**Pull request merged**
