### PR TITLE
update dependencies.tsv

### PR DESCRIPTION
**Pull request by makyo**
This updates dependencies in preparation for a build.  Minor change, but requesting multiple QAs to ensure everything works.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/543/

**Comment by makyo** [comment]
Here's one positive QA: 
screenshot from 2014-11-14 13 57 57

More would be appreciated

**Comment by mitechie** [comment]
That looks pretty. If you give me a idiots guide to running the CS I'll help QA.

**Comment by makyo** [comment]
# QA
- Fetch the charmstore and run it: 
  
  ```
  go get github.com/juju/charmstore/...
  cd $(GOHOME)/src/github.com/juju/charmstore
  git qa-pr origin 220 qa-220
  make sysdeps
  make deps
  # if mongo isn't running, start it with mongod
  make server
  ```
- Fetch the charmstore-client and ingest some charms
  
  ```
  go get github.com/CanonicalLtd/charmstore-client/...
  cd $(GOHOME)/src/github/CanonicalLtd/charmstore-client
  make sysdeps
  make deps
  make install
  charmload -config=../../juju/charmstore/cmd/charmd/config.yaml
  ```
- Watch the ingest go by watching the API server /debug/status until you have about 1220 charms ingested.  At this point, you can kill the ingest process and tell charmload to only ingest bundles, but continue watching the debug endpoint to see when any were properly ingested:

```
charmload -config=../../juju/charmstore/cmd/charmd/config.yaml -match="bundle"
```
- Search for bundles that were loaded in mongo

```
$ mongo juju
> db.entities.find({bundledata: {$ne: null}}, {entityid: 1})
{ "_id" : "cs:the/bundle/id" }
```
- Navigate to the that bundle's diagram.svg endpoint (eg: http://localhost:8080/v4/~a.rosales/bundle/storm-0/diagram.svg) and ensure that the bundle vis displays properly.  All other endpoints should load properly (minus search, if essync hasn't been run)

**Comment by mitechie** [comment]
I've managed to get things installed and charmload running. I'll continue QA once the charms catches up. Thanks for the instructions. The one missing bit was I had to change my git clone from the original 'go get' to v4 before setting up the qa-pr.

**Comment by mitechie** [comment]
QA ok! Thanks for the great instructions @makyo

**Comment by mitechie** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
