### PR TITLE
dependencies update

### PR DESCRIPTION
**Pull request by mhilton**
Make dependencies suitable for csclient.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: ship it

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/899/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/900/
Test PASSed.

**Comment by mhilton** [comment]
:shipit:

**Comment by urosj** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://localhost:8080/job/charmstore-merge

**Pull request merged**
