### PR TITLE
update dependencies.tsv

### PR DESCRIPTION
**Pull request by rogpeppe**
We want to use the latest version of the testing repository.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: That looks like it must be exactly the right commit hash.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/504/

**Comment by jrwren** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
