### PR TITLE
use external csclient, params

### PR DESCRIPTION
**Pull request by rogpeppe**
Remove csclient and params packages.
Also use charm.v6-unstable and update jujusvg dependency
to version that uses charm.v6-unstable.

No manual edits were made to this branch - just
running govers, rm and godeps.

This branch will be targetted to the new v5 branch.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/929/
Test FAILed.

**Comment by urosj** [comment]
:+1:

**Comment by mhilton** [comment]
LGTM, although it would be good to get CI sorted before this lands.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/955/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/956/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/960/
Test FAILed.

**Comment by rogpeppe** [comment]
Abandoned in favour of a PR that targets v5-unstable directly.

**Pull request closed without merging**
