### PR TITLE
internal/charmstore: factor out addentity tests

### PR DESCRIPTION
**Pull request by rogpeppe**
In preparation for adding tests of the logic now moved to internal/charmstore,
we move test for the code in addentity.go to addentity_test.go.
No changes other than code movement and the creation of a new
test suite.

### CODE REVIEW

**Comment by frankban** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1499/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
