### PR TITLE
internal/blobstore: upgrade goose version

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2158/

**Review by urosj — APPROVED** [review]

**Comment by mhilton** [comment]
:shipit:

**Comment by urosj** [comment]
Not just goose upgrade, but also buffered read.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
