### PR TITLE
Fix stats when a charm becomes a multi series charms by aggregating the stats from previous series.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1832/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by jrwren** [comment]
👍

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
