### PR TITLE
internal/charmstore: no error when specifying a channel with explicit revno

### PR DESCRIPTION
**Pull request by rogpeppe**
It seems reasonable to be liberal when an explicit revision is provided, and
this will also allow us to use the channel attribute in meta/perm to
specify a channel different from that of the entity that was resolved.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1574/
Test PASSed.

**Comment by frankban** [comment]
:+1: ty!

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
