### PR TITLE
Add meta/owner endpoint

### PR DESCRIPTION
**Pull request by mhilton**
Add id/meta/owner endpoint.

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM, thanks for getting it together to do this :)

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1688/
Test FAILed.

**Comment by urosj** [comment]
This one is not so trivial. https://api.jujucharms.com/charmstore/v5/keystone/meta/extra-info state that the owner of a promulgated charm is not "charmers" but "openstack-charmers".

**Comment by urosj** [comment]
:+1: QA :ok:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1689/
Test PASSed.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
