### PR TITLE
Bump juju/utils dependency w/ fixes.

### PR DESCRIPTION
**Pull request by Veebers**
Bumped juju/utils version in juju/juju which broke charmstore.v5 due to API changes.

Update charmstore.v5 in regards to those API changes (as well as bump the juju/utils version to match too).

### CODE REVIEW

**Comment by Veebers** [comment]
This is essentially the same as the changes I proposed against v5-unstable.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2172/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2173/

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
