### PR TITLE
Add base entities migration.

### PR DESCRIPTION
**Pull request by frankban**
It creates base entities if required.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/687/
Test PASSed.

**Comment by urosj** [comment]
:+1: Thanks.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
