### PR TITLE
update README

### PR DESCRIPTION
**Pull request by rogpeppe**
This should mostly fix issue #160; the one main thing that's omitted
is point 4, because that's not possible to address without mentioning
the private repository.

I am slightly nervous too about introducing a --force-yes option - there's
a reason that unsigned repositories are considered dubious.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/502/

**Comment by makyo** [comment]
:+1: THanks for the updates

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
