### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by rogpeppe**

### CODE REVIEW

**Comment by rogpeppe** [comment]
:shipit:

**Comment by rogpeppe** [comment]
LGTM'd in person by Uros and Francesco

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/703/
Test PASSed.

**Pull request merged**
