### PR TITLE
List only the latest revision of entities.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1349/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by urosj** [comment]
Really nice and useful! Ty for this branch.

:+1: QA :ok:

**Comment by fabricematrat** [comment]
:shipit: thanks @mhilton && @urosj

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
