### PR TITLE
Make archive GET return the entity id in the response header.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM, thanks! Please update the API docs too to reflect this change.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/418/

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
Thank you both for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
