### PR TITLE
Update jujusvg dep

### LINKED ISSUE #524: charm icons in bundle preview are incorrectly masked with Firefox
For example when opening https://jujucharms.com/openstack-base/bundle/ with Firefox 44 on Ubuntu Desktop, the charm icons are incorrectly masked. See the image below.

bundle-preview

### PR DESCRIPTION
**Pull request by makyo**
Fixes #524 
Addresses CanonicalLtd/jujucharms.com#206

### CODE REVIEW

**Comment by makyo** [comment]
# QA

fetching a bundle diagram in firefox should produce a proper diagram, with no offset clip paths

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1515/
Test PASSed.

**Comment by mhilton** [comment]
:+1: No QA

**Comment by makyo** [comment]
:shipit: prior to existing work

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
