### PR TITLE
Fix the list of known series.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/511/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
