### PR TITLE
use latest version of all dependencies

### PR DESCRIPTION
**Pull request by rogpeppe**
Update to the latest version of all packages we depend on.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/638/

**Comment by frankban** [comment]
:+1:

**Comment by mattyw** [comment]
@rogpeppe I ended up here on my OCR day - if you still want this to land can we merge with trunk? otherwise LGTM

**Comment by rogpeppe** [comment]
long past time for this. abandoning.

**Pull request closed without merging**
