### PR TITLE
update dependencies for new charm package version

### PR DESCRIPTION
**Pull request by rogpeppe**
This makes many more existing bundles import correctly.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/316/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
