### PR TITLE
Revert "internal/blobstore: use different swift library"

### PR DESCRIPTION
**Pull request by mhilton**
This reverts commit 1f36a9cb2fa5888686649902f398cd09019ed635.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2245/

**Review by rogpeppe — APPROVED** [review]
LGTM, thanks. (I'm assuming this is all automatically reverted).

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2246/

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
