### PR TITLE
all: use charm URL not Reference

### PR DESCRIPTION
**Pull request by rogpeppe**
Mostly mechanical.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: great!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1257/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
