### PR TITLE
lppublish: fix limit

### PR DESCRIPTION
**Pull request by rogpeppe**
Since publishTips was introduced, the old limit counting was not
appropriate, as it would start again when ingesting bundles.

This fixes that.

### CODE REVIEW

**Comment by jrwren** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/333/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmstore-merge/110

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/334/

**Comment by rogpeppe** [comment]
:shipit:

**Pull request merged**
