### PR TITLE
internal/charmstore: return complete entities from search

### PR DESCRIPTION
**Pull request by mhilton**
The search results already always included the complete _source use that
to populate the result entity to be identical to the input.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2262/

**Review by hatched — APPROVED** [review]
Thanks @mhilton nice cleanup!

**Review by mhemmings — APPROVED** [review]

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
