### PR TITLE
Update license to LGPL everywhere.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: Thanks for that.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/591/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
