### PR TITLE
upgrade charm.v3 to support devices

### PR DESCRIPTION
**Pull request by ycliuhw**
upgrade charm.v3 to support devices

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2219/

**Review by wallyworld — APPROVED** [review]
You will need to add the latest svg dep before landing

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2220/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2221/

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
