### PR TITLE
remove search cache

### PR DESCRIPTION
**Pull request by mhilton**
Remove caching of search results.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1052/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit: thanks guys

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
