### PR TITLE
csclient: implement Client.PutExtraInfo

### PR DESCRIPTION
**Pull request by rogpeppe**
Implement PUT to the meta/extra-info endpoint.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/391/

**Comment by makyo** [comment]
:+1: looks good, thanks

**Comment by jrwren** [comment]
:+1:

**Comment by urosj** [comment]
:+1: Thank you.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
