### PR TITLE
lppublish: publish charms first

### PR DESCRIPTION
**Pull request by rogpeppe**
Previously some charms could be uploaded after some bundles
because the upload process happens concurrently.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/321/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/322/

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:+1: Thank you!

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
