### PR TITLE
internal/charmstore: copy bakery session appropriately

### PR DESCRIPTION
**Pull request by rogpeppe**
This means that the charmstore macaroon handling won't die
when mongo restarts or changes leader.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1066/
Test FAILed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by mhilton** [comment]
Still LGTM.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1067/
Test PASSed.

**Comment by urosj** [comment]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
