### PR TITLE
lppublish, charmload: no longer needed

### PR DESCRIPTION
**Pull request by rogpeppe**
We move the BzrDigest key to params.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: thank you!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/405/

**Comment by mhilton** [comment]
:+1: Looks good

**Comment by jrwren** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
