### PR TITLE
search uses autocomplete=1 by default

### PR DESCRIPTION
**Pull request by jrwren**
Add autocomplete=1 by default so that old GUI clients return sane
results in search.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1860/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks!

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
