### PR TITLE
Move the debug/status endpoint tests to their own test file.

### PR DESCRIPTION
**Pull request by frankban**
This is a mechanical change.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/670/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:ship:
Thank you!

**Comment by frankban** [comment]
:shipit: even

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
