### PR TITLE
internal/charmstore: add migration step for revisions collection

### PR DESCRIPTION
**Pull request by rogpeppe**
Also remove unneeded migrations.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2076/

**Review by mhilton — APPROVED** [review]
LGTM

**Review by fabricematrat — APPROVED** [review]

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
