### PR TITLE
read IdentityLocation from config

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM, thanks!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/700/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
