### PR TITLE
Implement set-auth-cookie API endpoint.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1127/
Test PASSed.

**Comment by jrwren** [comment]
:+1:

**Comment by fabricematrat** [comment]
:+1:

**Comment by makyo** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
