### PR TITLE
Use ES _aliases, which returns json, for easier parsing.

### PR DESCRIPTION
**Pull request by bac**
The old endpoint on elasticsearch returned a string, which had to be parsed. Easier to get digestible JSON.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/368/

**Comment by jrwren** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by bac** [comment]
:ship: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
