### PR TITLE
csclient: implement Put

### PR DESCRIPTION
**Pull request by rogpeppe**
This makes it easier to access PUT-based methods in the charmstore.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/889/
Test PASSed.

**Comment by frankban** [comment]
:+1: thank you!

**Comment by mhilton** [comment]
:+1: LGTM thanks

**Comment by frankban** [comment]
:shipit:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
