### PR TITLE
docs: update promulgation documentation

### PR DESCRIPTION
**Pull request by rogpeppe**
This clarifies the new promulgation behaviour.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1767/
Test PASSed.

**Comment by urosj** [comment]
👍 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
