### PR TITLE
internal/blobstore: implement garbage collection

### PR DESCRIPTION
**Pull request by rogpeppe**
After some experimentation, it seems that holding
all the hashes in memory is a reasonable approach.
Currently there are ~45000 blobs in the store, giving
a projected memory usage of ~2.5MB for a GC.
This implementation should scale reasonably up
to 1 million blobs (20x current usage) and to 10 million
with minor changes. Beyond that, we may need to
use a different algorithm, but that should be OK
to do without changing the database.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2132/

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2133/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2134/

**Review by mhilton — APPROVED** [review]
Still LGTM

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2135/

**Review by fabricematrat — APPROVED** [review]
LGTM
Don't know if it will be hard to add a test where the put on blob is modify after the select.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
