### PR TITLE
Remove obsolete migrations.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1864/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by urosj** [comment]
👍

**Comment by urosj** [comment]
@frankban Please add a comment that any old DBs need to be deleted if migrations fail.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
