### PR TITLE
Add mongodb server as a dependency

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by frankban** [comment]
:+1: thanks!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/290/

**Comment by mitechie** [comment]
:+1:

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
