### PR TITLE
internal/v4: implement extra-info GET and PUT

### PR DESCRIPTION
**Pull request by rogpeppe**
We also change a bunch of ErrNotFound returns to use WithCausef
to aid error diagnosis.

We store the extra-info values as raw JSON, so that we're guaranteed
a correct round trip through mongo.

There are a bunch of changes to internal/v4/relations_test.go that
I didn't make and don't expect to see. Weird.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/176/

**Comment by jrwren** [comment]
A few tests fail for me on a clean checkout of this branch. All are of the same pattern:

AIL: api_test.go:560: APISuite.TestMetaCharmNotFound

test 0: charm-config
JSON call, url "/v4/precise/wordpress-23/meta/charm-config"
api_test.go:572:
    storetesting.AssertJSONCall(c, storetesting.JSONCallParams{
        Handler:      s.srv,
        URL:          storeURL("precise/wordpress-23/meta/" + ep.name),
        ExpectStatus: http.StatusNotFound,
        ExpectBody:   expected,
    })
/Users/jrwren/go/src/github.com/juju/charmstore/internal/storetesting/http.go:95:
    c.Assert(gotBodyVal, jc.DeepEquals, expectBodyVal)
... obtained map[string]interface {} = map[string]interface {}{"Message":"<no error>", "Code":"not found"}
... expected map[string]interface {} = map[string]interface {}{"Message":"not found", "Code":"not found"}
... mismatch at ["Message"]: unequal; obtained "<no error>"; expected "not found"

**Comment by rogpeppe** [comment]
Ah yes, there's a trivial update to errgo that this depends on that I
haven't pushed yes. Will try to do that.

**Comment by rogpeppe** [comment]
Fixed up and merged by Francesco.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/197/

**Pull request closed without merging**
