### PR TITLE
lppublish: make charm URLs correct earlier

### PR DESCRIPTION
**Pull request by rogpeppe**
This fixes a bug which would cause bundles to be processed
every time even when already in the store.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/287/

**Comment by jrwren** [comment]
:+1: 

Thanks for this. I had incorrectly thought that bundles were promulgated like charms, by using the OfficialSeries field in lpad api. They aren't and OfficialSeries is always empty for bundles so this works.

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
