### PR TITLE
Populate blobhash256 when entities are uploaded.

### PR DESCRIPTION
**Pull request by frankban**
Also add a script to update all entities with no
blobhash256, to be run once in the server and discarded.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/755/
Test PASSed.

**Comment by makyo** [comment]
:+1: from me, though you will probably want additional reviewers more familiar with Go (I know @rogpeppe had a question about doing this as a migration rather than a command).  Wasn't able to get a store up to QA this, unfortunately, due to some stale repos.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
