### PR TITLE
match wily correctly in FindBestEntity and also in search

### PR DESCRIPTION
**Pull request by mhilton**
Add wily and vivid to the filtering and search mappings.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1165/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by urosj** [comment]
No QA for now.

**Comment by urosj** [comment]
:+1:  QA

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
