### PR TITLE
remote legacy API info from README

### PR DESCRIPTION
**Pull request by rogpeppe**
It's misleading and unnecessary.

### CODE REVIEW

**Comment by frankban** [comment]
This is the only documentation for the legacy API we have. I agree it should not be in the main README, but I'd prefer to still keep the file somewhere, e.g. legacy-api.md or similar.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/396/

**Comment by jrwren** [comment]
:+1: s/remote/remove/ in the commit message.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/403/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
