### PR TITLE
use ppa:ubuntu-lxc/lxd-stable for go binaries

### PR DESCRIPTION
**Pull request by jrwren**
instead of juju/golang ppa.

### CODE REVIEW

**Comment by jrwren** [comment]
juju/golang ppa co-installs golang 1.6 rather than replacing golang 1.2. This prevents the go commands in this make file from actually working.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1938/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
