### PR TITLE
internal/router: allow top level meta endpoint list

### PR DESCRIPTION
**Pull request by rogpeppe**
We want to be able to find all meta endpoints without
necessarily inventing an entity id.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/432/

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
