### PR TITLE
Add test on header for Bakery Version Protocol v1.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1142/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
