### PR TITLE
internal/charmstore: allow adding resource with specific revision

### PR DESCRIPTION
**Pull request by rogpeppe**
This is a preparatory step before allowing PUT of resources
in the v5 API.

### CODE REVIEW

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2243/

**Review by urosj — APPROVED** [review]
LGTM if in next PR PUT is restricted to admins. Thanks.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
