### PR TITLE
Use charm.MustParseReference.

### PR DESCRIPTION
**Pull request by frankban**
Mostly mechanical, except for mustParseReferences (trailing slash).

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/412/

**Comment by jrwren** [comment]
:+1:

**Comment by urosj** [comment]
:+1: Time to panic!

**Comment by frankban** [comment]
Thanks for the reviews.
:ship:

**Comment by frankban** [comment]
:shipit: even...

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
