### PR TITLE
Move elasticsearch out of internal.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by fabricematrat** [comment]
QA:

A simple working make check should make sure all the bits are in the right order.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1094/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM, feel free to land.

**Comment by urosj** [comment]
:+1:

**Comment by fabricematrat** [comment]
:shipit: thanks @rogpeppe && @urosj

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
