### PR TITLE
update dependencies.tsv

### PR DESCRIPTION
**Pull request by rogpeppe**
This includes the bionic series support in utils/series.

### CODE REVIEW

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2163/

**Pull request merged**
