### PR TITLE
all: use params.Channel

### PR DESCRIPTION
**Pull request by rogpeppe**
This is an entirely mechanical change. We also update the dependencies
to use the new-channels-model branch of charmrepo.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: mechanical.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1594/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
