### PR TITLE
internal/charmstore: copy stats logic from _old

### PR DESCRIPTION
**Pull request by rogpeppe**
Please note that almost all the code and tests in this PR are already reviewed
and battle-tested.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/50/

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/51/

**Comment by jrwren** [comment]
LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/52/

**Comment by frankban** [comment]
:+1: Thanks.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
