### PR TITLE
Update endpoints' docstrings to point to the API doc in th repo.

### PR DESCRIPTION
**Pull request by frankban**
Remove all references to the old google drive documentation.
Add missing endpoints documentation (for instance, archive/path and meta/perm)
and fix some outdated/wrong bits (like meta/archive-upload-time).

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/752/
Test PASSed.

**Comment by jrwren** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/753/
Test PASSed.

**Comment by makyo** [comment]
:+1: Looks good, thanks for all the refs.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
