### PR TITLE
internal: add zesty to series

### PR DESCRIPTION
**Pull request by mhilton**
Add "zesty" to the lists of series and remove the now unsupported "wily" from search results.

### CODE REVIEW

**Review by frankban — APPROVED** [review]

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1907/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1908/
Test PASSed.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
