### PR TITLE
reenable tests when ES disabled; remove ElasticSearchTestPackage

### PR DESCRIPTION
**Pull request by rogpeppe**
Any package that was using ElasticSearchTestPackage would
have all its tests disabled when JUJU_TEST_ELASTICSEARCH=none.
This avoids that behaviour.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/437/

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/438/

**Comment by mhilton** [comment]
:+1: Other than the fact if doesn't compile this works great with and without elasticsearch.

**Comment by bac** [comment]
:+1:  when the unused import issue is fixed.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/439/

**Pull request merged**
