### PR TITLE
Remove legacy code.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/228/

**Comment by rogpeppe** [comment]
LGTM, thanks

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:shipit: thanks for the reviews

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
