### PR TITLE
internal/v4: disallow names from charm templates

### PR DESCRIPTION
**Pull request by rogpeppe**
This implements some extra checks required to keep dubious looking
charms out of the charm store.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/546/

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
Was paired on so...

:shipit:

**Comment by urosj** [comment]
:+1:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by urosj** [comment]
Hehe, shipped while reviewed.

**Pull request merged**
