### PR TITLE
params: rename content header

### PR DESCRIPTION
**Pull request by rogpeppe**
We just found out that Go canonicalises headers, so the all-caps SHA was
not appropriate.

### CODE REVIEW

**Comment by urosj** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/409/

**Comment by jrwren** [comment]
:+1: interesting.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
