### PR TITLE
fix example urls in API.md

### PR DESCRIPTION
**Pull request by jrwren**
stats/counter/archive-download not stats/counter/download or stats/counter/download/archive-download

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2099/

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
