### PR TITLE
all: use bundle/wordpress-simple in tests

### PR DESCRIPTION
**Pull request by rogpeppe**
Also update dependencies to use wordpress-simple bundle
from the updated charm.v4 package.

### CODE REVIEW

**Comment by jrwren** [comment]
:+1: QA with go test & go build and all is well.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/489/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
