### PR TITLE
internal/charmstore: add migrations for pre-v5 compatibility blobs

### PR DESCRIPTION
**Pull request by rogpeppe**
We also unexport the charmstore.addParams fields because they
no longer need to be public.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1511/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
