### PR TITLE
internal/charmstore: implement migrations for new channels model

### PR DESCRIPTION
**Pull request by rogpeppe**
Two commits: we first merge v5-unstable, then make the actual changes.
Best to comment on the latest commit.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1630/
Test PASSed.

**Comment by mhilton** [comment]
:+1: with a couple of comments

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1631/
Test PASSed.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
