### PR TITLE
internal/blobstore: buffer uploads to swift

### PR DESCRIPTION
**Pull request by mhilton**
Swift uploads were previously buffered internally in the goose
library. This makes the buffering more explicit and uses disk storage
if necessary.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2222/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2223/

**Review by mhemmings — APPROVED** [review]
LGTM (as much as it can right now!)

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2250/

**Pull request merged**
