### PR TITLE
Override CORS header in the set-auth-cookie endpoint so that xhr requests can set cookies.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by makyo** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1129/
Test PASSed.

**Comment by jrwren** [comment]
:+1: TY

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
