### PR TITLE
internal/router: provide http request to meta handlers

### PR DESCRIPTION
**Pull request by rogpeppe**
We need this so that we can make permission checks in the meta query
with respect to HTTP headers.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/684/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
