### PR TITLE
internal/blobstore: fix seeking backwards

### PR DESCRIPTION
**Pull request by rogpeppe**
Without the extra condition, we got a panic.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2057/

**Review by fabricematrat — APPROVED** [review]

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
