### PR TITLE
doc fix: use start and stop not from and to

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by urosj** [comment]
👍

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1703/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
