### PR TITLE
internal/v4: fix debug/status for new debug/status results

### PR DESCRIPTION
**Pull request by rogpeppe**
This also enables us to focus each test on the thing it's supposed to be testing.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/754/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
:+1: thank you!

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
