### PR TITLE
internal/router: add method argument to meta handlers

### PR DESCRIPTION
**Pull request by rogpeppe**
This will eventually enable us to PUT to meta endpoints.
Specific support for PUT will be added in a subsequent CL.

### CODE REVIEW

**Comment by frankban** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/97/

**Comment by jrwren** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
