### PR TITLE
internal/blobstore: avoid test duplication

### PR DESCRIPTION
**Pull request by rogpeppe**
The tests for the MongoDB object store and the
Swift object store were almost identical.
Avoid duplicating all the test code by factoring
the tests into a suite that's reused for each
backend.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2118/

**Review by mhilton — APPROVED** [review]
LGTM thanks for that

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
