### PR TITLE
internal/charmstore: fix add-preV5blob migration

### PR DESCRIPTION
**Pull request by rogpeppe**
The test wasn't testing anything, it turns out. We have now made a more failsafe
test and QA'd the migration.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1598/
Test PASSed.

**Comment by jrwren** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
