### PR TITLE
internal/v4: fix doc links

### PR DESCRIPTION
**Pull request by rogpeppe**
forgot to add to previous PR.

### CODE REVIEW

**Comment by rogpeppe** [comment]
Trivial, so...

:shipit:

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/863/
Test PASSed.

**Pull request merged**
