### PR TITLE
internal/charmstore: new migration tests

### PR DESCRIPTION
**Pull request by rogpeppe**
This hopefully gives considerably more assurance that the migrations will
work for real.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1628/
Test PASSed.

**Comment by urosj** [comment]
:+1: Looks good, thanks!

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
