### PR TITLE
Charm v5

### PR DESCRIPTION
**Pull request by frankban**
Mechanical branch.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/894/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
Thank you Uros for the review.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
