### PR TITLE
params: rename content hash header

### PR DESCRIPTION
**Pull request by rogpeppe**
As suggested by Francesco in previous review.

### CODE REVIEW

**Comment by frankban** [comment]
:+1:

**Comment by jrwren** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/407/

**Pull request merged**
