### PR TITLE
internal/charmstore: remove entity if ES insert fails

### PR DESCRIPTION
**Pull request by rogpeppe**
This was one reason we were seeing errors
in meta/manifest responses.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/493/

**Comment by jrwren** [comment]
:+1: QA with test and build. QA by attempting to post a charm when server elasticsearch is misconfigured. Response is 500 and subsequently trying to pull that charm data responds with 404.

**Comment by urosj** [comment]
:+1:

**Comment by urosj** [comment]
:shipit: (wanted to fix the ingested content)

**Pull request merged**
