### PR TITLE
internal/v4: add viewbox to icons that do not have one

### PR DESCRIPTION
**Pull request by rogpeppe**
Some web browsers require a viewbox, but not all icon.svg
files have one. The standard library's encoding/xml package
does not cope well with name spaces, so we use a temporarily
forked version with fixes.

We could be more efficient when processing icon.svg files
that already have a viewbox, but since icons will be cached
anyway and it's reasonably efficient, we use the simplest approach.

This is an updated version of PR #235

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/614/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/615/

**Comment by frankban** [comment]
:+1: thank you!

**Comment by makyo** [comment]
Generally :+1: with two QA issues.
1. there is content between the processing instruction and the root tag, which causes Chrome to throw the error "error on line 1 at column 52: Document is empty".  The content is &amp;#xA;, which is the unicode escape for a newline, I believe. Since it's not _actually_ whitespace, the SVG renderer throws a fit.
2. There is content after the closing root tag, &amp;#xA; again, which causes a similar error.

#235 got around these through a type-switch statement when iterating over tokens and throwing out extra CharData tokens outside of the root tag (but not within the root tag, since some icons have text as part of the icon itself - see cs:precise/zookeeper which has a 'Z' as part of the icon), which we might need to do here as well.

This might be worth fixing in github.com/juju/xml and filing a bug upstream again, not sure.

**Comment by rogpeppe** [comment]
Fixed in github.com/juju/xml by https://github.com/juju/xml/pull/2,
added a test and updated the dependencies accordingly.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/615/

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmstore-merge/200

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/618/

**Pull request merged**
