### PR TITLE
Stats update to be called from an agent

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1454/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1455/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by makyo** [comment]
:+1:

**Comment by fabricematrat** [comment]
:shipit:  thanks @mhilton && @makyo

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
