### PR TITLE
update for new charm.v3 API

### PR DESCRIPTION
**Pull request by rogpeppe**
Also update dependencies.tsv appropriately.

### CODE REVIEW

**Comment by jrwren** [comment]
LGTM

**Comment by rogpeppe** [comment]
Merging with only one review because this is a mechanical change.

:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/72/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/73/

**Pull request merged**
