### PR TITLE
v1/internal: Idempotent migration for blobrefs, no dropping of the collection.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2150/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2151/

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
