### PR TITLE
Unexport DenormalizeEntity

### PR DESCRIPTION
**Pull request by mhilton**
Stop using DenormalizeEntity in the one test outside of charmstore so that
the function can be unexported.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1198/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM thanks a lot for taking the time.

**Comment by urosj** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit: Thanks for the reviews

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
