### PR TITLE
internal/blobstore: always read full blob from swift

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by fabricematrat** [comment]
LGTM

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2159/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
