### PR TITLE
Update config values for idm defaults

### PR DESCRIPTION
**Pull request by bac**
In the default config file, update the port and public key for the identity manager.

### CODE REVIEW

**Comment by bac** [comment]
This is a very trivial change, part of an effort to make all of our services have reasonable, non-conflicting defaults.  The goal is to be able to run the equivalent of 'make server' in each to get cooperating services up and running with a minimal of editing of config files.

Most of the changes will be made to blues browser.

The default ports are
8080 - charmstore
8081 - idm

Omnibus has agreed to move their ports to a range starting at 8580 so we won't bump into them.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/783/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM I do wonder if this should be the details for api.jujucharms.com/identity though, that might make it easier to work on the charmstore without any other infrastructure.

**Comment by bac** [comment]
@mhilton I was trying to unify all of the default configs for running services locally, which is how this one was originally set up. If you think it makes more sense to do api.jujucharms.com/identity then we can do that and keep the other setting in the file but commented out, for ease of use when needed.  Do you have the public key for production identity?

**Comment by mhilton** [comment]
@bac hmHaPgCC1UfuhYHUSX5+aihSAZesqpVdjRv0mgfIwjo= just so you know you can get it from https://api.jujucharms.com/identity/v1/discharger/publickey

**Comment by rogpeppe** [comment]
LGTM, thanks.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/797/
Test PASSed.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
