### PR TITLE
set cookie path to /; add CORS header

### PR DESCRIPTION
**Pull request by jrwren**
add Access-Control-Expose-Headers

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1140/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
