### PR TITLE
all: use charm.v4

### PR DESCRIPTION
**Pull request by rogpeppe**
This is an almost entirely mechanical change, made by running "govers gopkg.in/juju/charm.v4".

### CODE REVIEW

**Comment by rogpeppe** [comment]
Note that dependencies.tsv is not yet updated because charm.v4 has not yet landed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/69/

**Comment by jrwren** [comment]
LGTM

**Comment by frankban** [comment]
:+1:  We just need to also update the dependencies file for this to be landed.

**Comment by frankban** [comment]
Closing because we no longer need this.

**Pull request closed without merging**
