### PR TITLE
remove identity api url.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Review by bac — APPROVED** [review]
That's some mighty good removing.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2083/

**Review by rogpeppe — COMMENTED** [review]
LGTM, thanks.

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
