### PR TITLE
Update 'go get' instructions.

### PR DESCRIPTION
**Pull request by bac**
Update instructions for use of 'go get'.  The -t causes test dependencies to be fetched. The '...' allows all dependencies to be fetched.

The original intent may have been to not use '...' but rely on the use of godeps to get everything at the correct version. Unfortunately it did not work as it didn't fetch missing packages.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/1/

**Comment by rogpeppe** [comment]
LGTM

**Comment by bac** [comment]
:shipit:

**Comment by bac** [comment]
I really wish we used :ship: instead.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
