### PR TITLE
internal/*: fixes for dependency changes

### PR DESCRIPTION
**Pull request by rogpeppe**
We also update to the latest version of the dependencies.

This makes the tests actually pass.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1183/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1184/
Test PASSed.

**Comment by frankban** [comment]
:+1: ty!

**Comment by fabricematrat** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
