### PR TITLE
cmd/charmd: update to use gopkg.in/yaml.v1

### PR DESCRIPTION
**Pull request by rogpeppe**
This brings us into line with juju-core, which has just changed to
do the same.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/118/

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
