### PR TITLE
reformat dependencies.tsv with UTC times

### PR DESCRIPTION
**Pull request by rogpeppe**
No actual dependency changes here.

### CODE REVIEW

**Comment by frankban** [comment]
:+1:

**Comment by urosj** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/613/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
