### PR TITLE
Merge changes from master.

### PR DESCRIPTION
**Pull request by frankban**
Mechanical, only conflict in router.go.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1264/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
Thanks for the review!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
