### PR TITLE
charmd: use identity URL

### PR DESCRIPTION
**Pull request by mhilton**
Add the configuration to the charmd command so that charmstore can retrieve group information from IdM.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/918/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by urosj** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://localhost:8080/job/charmstore-merge

**Pull request merged**
