### PR TITLE
internal/v5: add promulgated-id and unpromulgated-id endpoints

### PR DESCRIPTION
**Pull request by rogpeppe**
Currently there is no easy way to find out the canonical entity
Id from an arbitrary id, nor is there a way to find the promulgated
id. This adds both those as meta endpoints.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2248/

**Review by urosj — APPROVED** [review]
LGTM

**Review by mhemmings — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
