### PR TITLE
Updated jujusvg to limit visualisation size.

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/682/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by urosj** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit: trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
