### PR TITLE
internal/router: add some more comments

### PR DESCRIPTION
**Pull request by rogpeppe**
As suggested by frankban in https://github.com/juju/charmstore/pull/39.

I started trying to add some sort of example to the FieldIncludeHandler
doc comment, but didn't do very well, so fell back to just pointing
to the best example we have.

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by frankban** [comment]
:+1: thank you!

**Comment by urosj** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
