### PR TITLE
internal/storetesting: add YAMLEquals checker

### PR DESCRIPTION
**Pull request by rogpeppe**
We want this for checking YAML output elsewhere.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/431/

**Comment by mhilton** [comment]
:+1: Nice

**Comment by jrwren** [comment]
:+1: really nice.

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/500/

**Pull request merged**
