### PR TITLE
Fix pprof generated index html.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/660/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM, thanks!

**Comment by rogpeppe** [comment]
(No QA)

**Comment by frankban** [comment]
:shipit: trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
