### PR TITLE
internal/charmstore: fix autocomplete

### PR DESCRIPTION
**Pull request by mhilton**
Change the way autocomplete searches are performed to only match entities where text is an exact prefix of the entity name.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1776/
Test PASSed.

**Comment by jrwren** [comment]
👍

**Comment by frankban** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by rogpeppe** [comment]
LGTM

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
