### PR TITLE
Expose a testing server to be used from outside.

### PR DESCRIPTION
**Pull request by frankban**
Also add teh ability to upload charms to the server.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/840/
Test PASSed.

**Comment by jrwren** [comment]
:+1:

**Comment by hatched** [comment]
Looks good :+1: Thanks!

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
