### PR TITLE
filter the changes/published endpoint to only show charms the user can see

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1109/
Test PASSed.

**Comment by urosj** [comment]
:+1: on code, doing QA now

**Comment by urosj** [comment]
QA worked as well

**Comment by jrwren** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
