### PR TITLE
internal/charmstore: reuse macaroon root keys

### PR DESCRIPTION
**Pull request by rogpeppe**
This takes advantage of the mgostorage.RootKeyStorage to avoid
generating root keys every time we make an authorization decision.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1778/
Test FAILed.

**Comment by mhilton** [comment]
:+1: once everything lands

**Comment by jrwren** [comment]
👍

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1781/
Test PASSed.

**Pull request merged**
