### PR TITLE
lppublish: fix publishing of promulgated charms

### PR DESCRIPTION
**Pull request by rogpeppe**
The same body can be posted several times, but it was closed after
the first request. This stops that happening.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/250/

**Comment by urosj** [comment]
:+1: Good catch, thank you.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
