### PR TITLE
all: use charm.v4

### PR DESCRIPTION
**Pull request by rogpeppe**
Automatic change made by running:

```
govers gopkg.in/charm.v4
govers -m launchpad.net/gocheck gopkg.in/check.v1
```

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/285/

**Comment by jrwren** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
