### PR TITLE
depenency update

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM
1 review surely ok for this

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1286/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
