### PR TITLE
Switch to using gopkg.in/juju/charmstore.v4

### PR DESCRIPTION
**Pull request by frankban**
Makefile and readme updated manually.
All the other changes are mechanical, done using govers and sortimports.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/786/
Test FAILed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/790/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM, thanks.

**Comment by frankban** [comment]
Thank you, trying to merge it.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
