### PR TITLE
Fix the charmstoretesting server so that it is backward compatible.

### PR DESCRIPTION
**Pull request by frankban**
Always make the charms public when using UploadCharm.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/949/
Test PASSed.

**Comment by mhilton** [comment]
:+1: thanks

**Comment by frankban** [comment]
Thanks for the review Martin.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
