### PR TITLE
move to charmrepo.v3

### PR DESCRIPTION
**Pull request by rogpeppe**
This uses the charmrepo repo that uses the same bakery version
as the charmstore, so the bakery.v1 dependency goes away.

Also update the juju/testing dependency to latest master (compatible
with more recent mongod versions).

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2183/

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
