### PR TITLE
Mongodb log sorting

### PR DESCRIPTION
**Pull request by mhilton**
Sort the results of the log query correctly.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/657/

**Comment by urosj** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
