### PR TITLE
Add boosting of bundles.

### PR DESCRIPTION
**Pull request by mhilton**
Bundles are now boosted to be just above the highest series.

### CODE REVIEW

**Comment by mhilton** [comment]
To QA run charmd on a server with elasticsearch running and perform some queries. If all other things are equal bundles should come higher than trusty which comes higher than precise. But promulgated and other things and matches should still trump those.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/587/

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
