### PR TITLE
added additional indexes

### PR DESCRIPTION
**Pull request by mhilton**
Added the additional indexes suggested by @jrwren.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1026/
Test FAILed.

**Comment by mhilton** [comment]
Note CI failed for transitive reasons, being unable to contact the servers for some dependencies.

**Comment by urosj** [comment]
:+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
