### PR TITLE
internal/v5: allow PUT with channels

### PR DESCRIPTION
**Pull request by rogpeppe**
This will allow the ingester to upload entities to channels in a single
operation.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1638/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
