### PR TITLE
internal/charmstore: add more indexes

### PR DESCRIPTION
**Pull request by rogpeppe**
This should solve some performance issues.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1477/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by urosj** [comment]
:+1: , QA :ok:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
