### PR TITLE
internal/v5: implement PUT for resources

### PR DESCRIPTION
**Pull request by rogpeppe**
Note that this endpoint is still open for non-admins, just as charm PUT is
currently. That will probably change in a subsequent PR.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2244/

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
