### PR TITLE
Stub out the meta endpoint for resources.

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
The full implementation of the resources endpoints will be added later, after channels land.

(already reviewed in #563)

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1625/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1626/
Test PASSed.

**Comment by ericsnowcurrently** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
