### PR TITLE
all: use Equals nil not NotNil for error checks

### PR DESCRIPTION
**Pull request by rogpeppe**
Trivial automatic change. Also use Equals instead of jc.ErrorIsNil for
consistency and because ErrorIsNil doesn't add significant value.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2077/

**Review by fabricematrat — APPROVED** [review]

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
