### PR TITLE
internal/charmstore: fix trivial race in test

### PR DESCRIPTION
**Pull request by rogpeppe**
Detected by go test -race.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/990/
Test PASSed.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
