### PR TITLE
Remove uses of  charm.URL.Channel

### PR DESCRIPTION
**Pull request by babbageclunk**
This has been removed from charm.URL in the process of implementing http://pad.lv/1584193.

The only uses were checking that the url had no channel or removing the channel from a url.

Updated charm.v6-unstable dependency. This is arguably unnecessary, but it's safer - otherwise someone could pass in a charm url with a channel and this code would no longer strip it out.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1902/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1903/
Test PASSed.

**Review by frankban — APPROVED** [review]
Looks good, thanks for this!

**Comment by babbageclunk** [comment]
$$merge$$

**Comment by babbageclunk** [comment]
Oops, let's try :shipit:

**Comment by babbageclunk** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
