### PR TITLE
Added elasticsearch configuration to charmstore.

### PR DESCRIPTION
**Pull request by mhilton**
The config.yaml file can now contain an optional
elasticsearch-addr parameter specifying an
elasticsearch endpoint to connect to for searching.

### CODE REVIEW

**Comment by bac** [comment]
Looks good Martin.
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/329/

**Comment by jrwren** [comment]
:+1:

**Comment by jrwren** [comment]
QA both with and without elasticsearch-addr in config.  :+1:

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
