### PR TITLE
update charm dependencies

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Review by rogpeppe — APPROVED** [review]
LGTM

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2213/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
