### PR TITLE
internal/v4: export Handler

### PR DESCRIPTION
**Pull request by rogpeppe**
When implementing the legacy API we want access to parts of the v4 implementation
and this provides that.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/206/

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
:+1: thank you!

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/207/

**Pull request merged**
