### PR TITLE
V5 unstable updates 02

### PR DESCRIPTION
**Pull request by alesstimec**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1360/
Test PASSed.

**Comment by cmars** [comment]
Another way to look at this from a terms perspective is to [diff the proposed branch against v5-unstable](https://github.com/juju/charmstore/compare/v5-unstable...alesstimec:v5-unstable-updates-02), since that's what we want to do after this lands. That diff is much smaller (by a factor of 10!).

**Comment by cmars** [comment]
[Manually tested](https://github.com/cmars/omnibus-layers/tree/test-terms-v5-unstable-updates-02) deployment of a charm w/terms & a commercial charm, juju-1.26 client.

**Comment by cmars** [comment]
LGTM

**Comment by cmars** [comment]
Or, :+1: is how they say it round these parts.

**Pull request merged**
