### PR TITLE
lppublish: new package, factored from cmd/charmload

### PR DESCRIPTION
**Pull request by rogpeppe**
This prepares the way for writing some tests for the publish
functionality, taken from the old charm store code.
Done as a separate PR so that code movement is
kept distinct from code changes.

There is no new logic in this branch - all the charmLoader methods
are identical.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/243/

**Comment by urosj** [comment]
:+1: 
Please notify @jrwren and @frankban about this change.

**Comment by frankban** [comment]
:+1: thanks!

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
