### PR TITLE
use charm tags in search as well as categories

### PR DESCRIPTION
**Pull request by mhilton**
Use CharmMeta.Tags and CharmMeta.Categories in search queries.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/851/
Test PASSed.

**Comment by urosj** [comment]
/charmstore/search/queryFields should probably include Tags as well

**Comment by urosj** [comment]
Did QA, works fine.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/853/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM, thanks

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
