### PR TITLE
internal/charmstore: do not allow charms and bundles to have the same names

### PR DESCRIPTION
**Pull request by rogpeppe**
This enforces (with high probability) the flat name space we want for the future.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/491/

**Comment by jrwren** [comment]
:+1: I did rudimentary QA with go test and go build.  Nice new tests.

**Comment by frankban** [comment]
:shipit:

**Comment by frankban** [comment]
Thanks for the review and QA Jay!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
