### PR TITLE
Fix identity manager location.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/846/
Test PASSed.

**Comment by jrwren** [comment]
:+1: and thank you

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
Thank for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
