### PR TITLE
Added pagination to search queries

### PR DESCRIPTION
**Pull request by mhilton**
A new start parameter can be added to search queries and the results
will start from that offset in the overall search results.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/478/

**Comment by mhilton** [comment]
To QA start charmd with an attached elasticsearch and run queries with the start parameter to offset the results.

**Comment by jrwren** [comment]
:+1: QA is good too.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/479/

**Comment by urosj** [comment]
:+1: Excellent to see how little needs to be done in actual code to add pagination!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/480/

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
