### PR TITLE
add internal/storetesting JSONCallParams

### PR DESCRIPTION
**Pull request by rogpeppe**
This makes the tests look prettier and also
allows us to specify the body content
type without further burdening the call sites.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/65/

**Comment by jrwren** [comment]
LGTM

**Comment by makyo** [comment]
LGTM

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
