### PR TITLE
Is-entity caveat fix for the issued macaroons.

### PR DESCRIPTION
**Pull request by alesstimec**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1512/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1513/
Test PASSed.

**Comment by cmars** [comment]
There are a few places where the macaroon is minted. It's not obvious to me how the deny caveat fits into the macaroon challenge & discharge response data flow for getting user agreement to terms.

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1516/
Test PASSed.

**Comment by cmars** [comment]
LGTM QA :+1:

**Comment by alesstimec** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
