### PR TITLE
Support for windows and centos as "series"

### PR DESCRIPTION
**Pull request by urosj**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/877/
Test PASSed.

**Comment by jrwren** [comment]
:+1:

**Comment by urosj** [comment]
:shipit:

**Comment by urosj** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
