### PR TITLE
Update API.md

### PR DESCRIPTION
**Pull request by jrwren**
fix Promulgate field to Promulgated in PromulgateRequest struct.

### CODE REVIEW

**Comment by bac** [comment]
:+1:

:+1:

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore/1753/
Test PASSed.

**Pull request merged**
