### PR TITLE
internal/v4: implement meta/bundle-unit-count and meta/bundle-machine-count

### PR DESCRIPTION
**Pull request by rogpeppe**
As specified in the charm API document.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/201/

**Comment by frankban** [comment]
:+1:

**Comment by jrwren** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
