### PR TITLE
internal/v5: Support multiple values for filters.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by fabricematrat** [comment]
https://github.com/juju/charmstore-client/issues/11

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2228/

**Review by rogpeppe — APPROVED** [review]
LGTM thanks!

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
