### PR TITLE
csclient: make Do more general; make Get do more work

### PR DESCRIPTION
**Pull request by rogpeppe**
This will make it easier to implement archive downloading without
duplicating code.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/393/

**Comment by jrwren** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge

**Pull request merged**
